// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Store;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.modelos.ModelClass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ModelClasses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "first casa",
                            img = "https://www.puntodebreak.com/files/styles/eht/public/medvedev-prensa-seyboth-wild.jpg?itok=l74U9Mki",
                            name = "casa1",
                            price = 0,
                            quantity = 0
                        },
                        new
                        {
                            id = 2,
                            description = "secon casa",
                            img = "https://www.elgrafico.com.ar/media/cache/pub_news_details_large/media/i/c7/93/c793620737acdccd2d5b00b4d0f0483f613b22b6.jpg",
                            name = "casa2",
                            price = 0,
                            quantity = 0
                        },
                        new
                        {
                            id = 3,
                            description = "third casa",
                            img = "https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(webp):focal(1312x271:1314x269)/origin-imgresizer.eurosport.com/2023/03/22/3667442-74657768-2560-1440.jpg",
                            name = "casa3",
                            price = 0,
                            quantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
